# Generated by Django 4.1 on 2022-12-29 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('First_Name', models.CharField(max_length=50)),
                ('Middle_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='UNKNOWN', max_length=40)),
                ('Salutation', models.CharField(choices=[('MR', 'Mr.'), ('MASTER', 'Mst.'), ('MISS', 'Ms.'), ('MRS', 'Mrs.')], max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Contact_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Emergency_contact_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Date_of_Birth', models.DateField(null=True)),
                ('Address_line_1', models.CharField(max_length=300)),
                ('Address_line_2', models.CharField(max_length=300)),
                ('State', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Pincode', models.IntegerField(null=True)),
                ('Id_Proof_name', models.CharField(choices=[('AADHAR CARD', 'Aadhar Card'), ('PAN CARD', 'Pan Card'), ('PASSPORT', 'Passport')], default='AADHAR CARD', max_length=40)),
                ('Id_Proof_no', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='activities',
            fields=[
                ('activity_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=50)),
                ('is_present', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Current_Member_Membership',
            fields=[
                ('membership_no', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Payment_type', models.CharField(max_length=100)),
                ('Payment_date', models.DateField()),
                ('Amount', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('is_manager', models.BooleanField(default=True)),
                ('Manager_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('Member_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('is_member', models.BooleanField(default=True)),
                ('Member_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NormalStaff',
            fields=[
                ('Staff_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Staff_role', models.CharField(choices=[('RECEPTIONIST', 'Receptionist'), ('LIFE GUARD', 'Life Guard'), ('CLEANER', 'Cleaner'), ('HOUSE KEEPER', 'House Keeper')], default=None, max_length=40)),
                ('is_staff', models.BooleanField(default=True)),
                ('Staff_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Price_for_members',
            fields=[
                ('member_price_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('activity_price', models.IntegerField()),
                ('for_holiday', models.BooleanField(default=False)),
                ('Staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.normalstaff')),
                ('activity_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.activities')),
            ],
        ),
        migrations.CreateModel(
            name='Price_for_Guests',
            fields=[
                ('Guest_price_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('activity_price', models.IntegerField()),
                ('for_holiday', models.BooleanField(default=False)),
                ('Staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.normalstaff')),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.activities')),
            ],
        ),
        migrations.CreateModel(
            name='memberships_and_price',
            fields=[
                ('membership_data_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('membership_type', models.CharField(choices=[('ANNUAL', 'Annual'), ('6 MONTHS', '6 Months'), ('3 MONTHS', '3 Months')], max_length=40)),
                ('membership_price', models.IntegerField()),
                ('Staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.normalstaff')),
            ],
        ),
        migrations.CreateModel(
            name='Member_Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Payment_type', models.CharField(max_length=100)),
                ('Payment_date', models.DateField()),
                ('Amount', models.IntegerField(blank=True)),
                ('Staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.normalstaff')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.member')),
                ('membership_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.current_member_membership')),
                ('membership_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.memberships_and_price')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='Staff_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='management.normalstaff'),
        ),
        migrations.CreateModel(
            name='InoutEntry',
            fields=[
                ('InoutEntryid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('No_of_Guests', models.IntegerField()),
                ('Total_Amount', models.IntegerField(blank=True)),
                ('Payment_method', models.CharField(max_length=100)),
                ('Entered_date', models.DateField(auto_now_add=True)),
                ('Staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.normalstaff')),
                ('membership_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.current_member_membership')),
            ],
        ),
        migrations.CreateModel(
            name='InoutDetails',
            fields=[
                ('InoutDetailsId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('member_amount', models.IntegerField(blank=True)),
                ('Guest_count', models.IntegerField(blank=True)),
                ('Guest_Amount', models.IntegerField(blank=True)),
                ('Total_Activity_amount', models.IntegerField(blank=True)),
                ('Activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.activities')),
                ('Guest_rate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.price_for_guests')),
                ('InoutEntryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.inoutentry')),
                ('member_rate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.price_for_members')),
            ],
        ),
        migrations.AddField(
            model_name='current_member_membership',
            name='Staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.normalstaff'),
        ),
        migrations.AddField(
            model_name='current_member_membership',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.member'),
        ),
        migrations.AddField(
            model_name='current_member_membership',
            name='membership_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.memberships_and_price'),
        ),
        migrations.AddField(
            model_name='activities',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.normalstaff'),
        ),
    ]
