# Generated by Django 4.1 on 2023-01-03 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_price_for_members_activity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_type_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='management.memberships_and_price'),
            preserve_default=False,
        ),
    ]
