# Generated by Django 4.1 on 2023-01-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_member_membership_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='membership_type_id',
        ),
    ]
