# Generated by Django 4.1 on 2023-01-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_member_membership_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_member_membership',
            name='membership_no',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
